import os
from dotenv import load_dotenv 
load_dotenv() 


PDF_PATH = r"C:\\Users\\AIFA USER 285\\Multi_Agent\\Multi_Agent_02\\indian-penal-code.pdf"
VECTOR_DB_PATH = r"C:\\Users\\AIFA USER 285\\Multi_Agent\\Multi_Agent_02\\Indianpenalcode"



TAVILY_API_KEY  = "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"



AZURE_OPENAI_CM_API_KEY = os.getenv("AZURE_OPENAI_CM_API_KEY")
AZURE_OPENAI_CM_ENDPOINT = os.getenv("AZURE_OPENAI_CM_ENDPOINT")
AZURE_OPENAI_CM_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_CM_DEPLOYMENT_NAME")
AZURE_OPENAI_CM_API_VERSION = os.getenv("AZURE_OPENAI_CM_API_VERSION")
MODEL_TEMPERATURE = 0
 
AZURE_OPENAI_EMB_MODEL_NAME= os.getenv("AZURE_OPENAI_EMB_MODEL_NAME")
AZURE_OPENAI_EMB_DEPLOYMENT_NAME= os.getenv("AZURE_OPENAI_EMB_DEPLOYMENT_NAME")
AZURE_OPENAI_EMB_ENDPOINT= os.getenv("AZURE_OPENAI_EMB_ENDPOINT")
AZURE_OPENAI_EMB_API_KEY= os.getenv("AZURE_OPENAI_EMB_API_KEY")
AZURE_OPENAI_EMB_API_VERSION= os.getenv("AZURE_OPENAI_EMB_API_VERSION")

CHUNK_SIZE = 512
CHUNK_OVERLAP = 100
TOP_K = 4
TEMPERATURE = 0.3

MONGODB_URI = "mongodb+srv://raghuragoud_db_user:opXYXokCsJfmTo6N@cluster0.jnbea2t.mongodb.net/?appName=Cluster0"
MONGODB_DB_NAME = "multi_agent_system"